export const knowledgeEntries = [
  {
    id: "thin-layers",
    category: "技法",
    title: "薄髹与层积",
    english_title: "Thin Coating & Layering",
    summary: "漆器的深度不是一次覆盖，而是薄层反复髹涂、等待与打磨共同形成。",
    full_text: "每一层大漆都应薄而均匀。漆层需要在合适温湿度下干燥，再经过打磨后进入下一层。层与层之间的时间、厚度和手势共同决定最终表面。",
    image_url: "/demo/lacquer-bowl.png",
    steps: ["处理胎体", "薄而均匀地髹涂", "荫干等待", "细磨表面", "重复层积"],
    key_actions: ["控制厚度", "保持均匀", "判断干燥状态", "重复操作"],
    common_errors: ["单层过厚导致皱缩", "未干透即打磨", "边缘积漆"],
    expert_notes: ["光泽来自层次与工序，而不是一次性涂亮。", "等待不是空白，而是工艺的一部分。"],
    related_ids: ["harvesting", "polishing"],
    source: "漆问精选演示 · 用户提供素材 · 仅限内部演示",
    affordances: ["重复节奏", "厚度控制", "等待窗口", "均匀度反馈"],
  },
  {
    id: "harvesting",
    category: "工序",
    title: "割漆与采集",
    english_title: "Lacquer Harvesting",
    summary: "从漆树取得生漆，是一项受季节、时间与伤口尺度制约的工作。",
    full_text: "采漆需要在合适的季节与时段进行。割口过深会伤树，过浅则难以取得足量漆液。",
    image_url: "/demo/lacquer-forest.png",
    steps: ["观察树龄与天气", "选择割口", "控制深浅", "等待漆液", "收集与封存"],
    key_actions: ["观察", "轻割", "等待", "收集"],
    common_errors: ["割口过深", "不合时令", "容器污染"],
    expert_notes: ["采集是一种长期关系，不是一次性索取。"],
    related_ids: ["thin-layers"],
    source: "漆问精选演示 · 用户提供素材 · 仅限内部演示",
    affordances: ["风险收益", "季节窗口", "资源克制", "精确操作"],
  },
  {
    id: "polishing",
    category: "技法",
    title: "研磨与显光",
    english_title: "Polishing & Revealing",
    summary: "研磨既去除不平，也逐步揭示被层积包裹的纹理与光泽。",
    full_text: "研磨使用由粗到细的材料与手势。压力、方向和次数影响表面。",
    image_url: "/demo/lacquer-workshop.png",
    steps: ["检查干燥", "粗磨找平", "清洁表面", "细磨显光", "检查层次"],
    key_actions: ["调节压力", "改变方向", "观察反光", "及时停止"],
    common_errors: ["局部磨穿", "磨料残留", "压力不均"],
    expert_notes: ["好的研磨是一种逐渐显现，而不是快速抛亮。"],
    related_ids: ["thin-layers"],
    source: "漆问精选演示 · 用户提供素材 · 仅限内部演示",
    affordances: ["压力控制", "隐藏信息揭示", "风险阈值", "由粗到细"],
  },
];

export const demoAssets = [
  { id: "asset-1", type: "IMAGE", name: "漆林晨雾", url: "/demo/lacquer-forest.png", scope: "PROJECT" },
  { id: "asset-2", type: "IMAGE", name: "匠人作坊", url: "/demo/lacquer-workshop.png", scope: "PROJECT" },
  { id: "asset-3", type: "IMAGE", name: "未完成漆碗", url: "/demo/lacquer-bowl.png", scope: "LIBRARY" },
  { id: "asset-4", type: "3D", name: "LacquerBowl_v1", url: "/demo/lacquer-bowl-v1.glb", scope: "PROJECT" },
  { id: "asset-5", type: "AUDIO", name: "作坊静层", url: "/demo/main-theme.wav", scope: "PROJECT" },
  { id: "asset-6", type: "AUDIO", name: "采漆晨行", url: "/demo/harvest-theme.wav", scope: "LIBRARY" },
];
