"""MILESTONE 2 persistence baseline frozen at the M2 schema.

Revision ID: 20260810_0001
Revises: None
"""
from alembic import op

revision = "20260810_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    statements = [
        """CREATE TABLE knowledge_entries (id varchar(80) PRIMARY KEY, category varchar(80) NOT NULL, title varchar(200) NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL)""",
        """CREATE TABLE projects (id varchar(36) PRIMARY KEY, title varchar(240) NOT NULL, selected_knowledge_id varchar(80) NOT NULL REFERENCES knowledge_entries(id), current_stage varchar(40) NOT NULL, player_idea text NOT NULL DEFAULT '', progress integer NOT NULL DEFAULT 0, revision integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL)""",
        """CREATE TABLE conversation_messages (id varchar(36) PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, role varchar(24) NOT NULL, content text NOT NULL, provider varchar(100) NOT NULL, created_at timestamptz NOT NULL)""",
        """CREATE TABLE assets (id varchar(80) PRIMARY KEY, project_id varchar(36) REFERENCES projects(id) ON DELETE CASCADE, type varchar(24) NOT NULL, name varchar(240) NOT NULL, url text NOT NULL, scope varchar(24) NOT NULL, sha256 varchar(64), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL)""",
        """CREATE TABLE artifact_versions (id varchar(36) PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, kind varchar(32) NOT NULL, version integer NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL, CONSTRAINT uq_artifact_version UNIQUE(project_id, kind, version))""",
        """CREATE TABLE approvals (id varchar(36) PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, artifact varchar(32) NOT NULL, version integer NOT NULL, approved_at timestamptz NOT NULL, CONSTRAINT uq_approval_version UNIQUE(project_id, artifact, version))""",
        """CREATE TABLE activity_log (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, sequence integer NOT NULL, message text NOT NULL, created_at timestamptz NOT NULL, CONSTRAINT uq_activity_sequence UNIQUE(project_id, sequence))""",
        """CREATE TABLE provider_jobs (id varchar(36) PRIMARY KEY, project_id varchar(36) REFERENCES projects(id) ON DELETE CASCADE, provider varchar(80) NOT NULL, kind varchar(40) NOT NULL, status varchar(24) NOT NULL, idempotency_key varchar(180) NOT NULL UNIQUE, request_payload jsonb NOT NULL DEFAULT '{}'::jsonb, response_payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL)""",
        """CREATE TABLE outbox_events (id varchar(36) PRIMARY KEY, project_id varchar(36) REFERENCES projects(id) ON DELETE CASCADE, event_type varchar(80) NOT NULL, payload jsonb NOT NULL, idempotency_key varchar(180) NOT NULL UNIQUE, status varchar(24) NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL, processed_at timestamptz)""",
    ]
    for statement in statements:
        op.execute(statement)
    for table in ("conversation_messages", "assets", "artifact_versions", "approvals", "activity_log", "provider_jobs", "outbox_events"):
        op.execute(f"CREATE INDEX ix_{table}_project_id ON {table}(project_id)")


def downgrade() -> None:
    for table in ("outbox_events", "provider_jobs", "activity_log", "approvals", "artifact_versions", "assets", "conversation_messages", "projects", "knowledge_entries"):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
